// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-G5qlggVcFXiEown1cRF1KGd5Lt8wTNs',
    appId: '1:481289422128:web:822294f4c4afaf96d174f5',
    messagingSenderId: '481289422128',
    projectId: 'nyemangati-bf048',
    authDomain: 'nyemangati-bf048.firebaseapp.com',
    storageBucket: 'nyemangati-bf048.firebasestorage.app',
    measurementId: 'G-F9VLP1GD6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNaIjRy4RevCosA0YJulc5tLD0CcSP-0',
    appId: '1:481289422128:android:9cbba0b22050fbb3d174f5',
    messagingSenderId: '481289422128',
    projectId: 'nyemangati-bf048',
    storageBucket: 'nyemangati-bf048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDwLtKVAtvESYF8AwpTjiyGaL2lsH3U_Y',
    appId: '1:481289422128:ios:a310f4043217c0e9d174f5',
    messagingSenderId: '481289422128',
    projectId: 'nyemangati-bf048',
    storageBucket: 'nyemangati-bf048.firebasestorage.app',
    iosBundleId: 'com.example.nyemangati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDwLtKVAtvESYF8AwpTjiyGaL2lsH3U_Y',
    appId: '1:481289422128:ios:a310f4043217c0e9d174f5',
    messagingSenderId: '481289422128',
    projectId: 'nyemangati-bf048',
    storageBucket: 'nyemangati-bf048.firebasestorage.app',
    iosBundleId: 'com.example.nyemangati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-G5qlggVcFXiEown1cRF1KGd5Lt8wTNs',
    appId: '1:481289422128:web:cbdda254af749975d174f5',
    messagingSenderId: '481289422128',
    projectId: 'nyemangati-bf048',
    authDomain: 'nyemangati-bf048.firebaseapp.com',
    storageBucket: 'nyemangati-bf048.firebasestorage.app',
    measurementId: 'G-NBZFHK5N9Z',
  );
}
